backend:
  name: git-gateway
  repo: Symptom7489/pack156
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "leadership" # <-- Add this hyphen
    label: "Leaders"
    folder: "leadership"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Rank Photo", name: "rank_photo", widget: "image" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/leadership.njk" }

  - name: "adventures"
    label: "Adventures"
    folder: "adventures"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover Photo", name: "cover_photo", widget: "image", path: "{{slug}}/cover-{{extension}}" }
      - label: "Photos"
        name: "photos"
        widget: "list"
        required: false
        field: { label: "Photo", name: "photo", widget: "image", path: "{{slug}}/{{filename}}" }
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/adventures.njk" }
