backend:
  name: git-gateway
  repo: Symptom7489/pack156
  branch: main

media_folder: images/leadership
public_folder: /images/leadership

collections:
  - name: "leadershipo"
    label: "Leaders"
    folder: "leadership"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Rank Photo", name: "rank_photo", widget: "image" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/leadership.njk" }
      - { label: "Weight", name: "weight", widget: "number", default: 100 }
