backend:
  name: git-gateway
  repo: Symptom7489/dpec-test
  branch: main

media_folder: images/members
public_folder: /images/members

collections:
  - name: "members"
    label: "Members"
    folder: "members"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Pronouns", name: "pronouns", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown" }
      - { label: "Name", name: "layout", widget: "hidden", default: "layouts/members.njk" }
      - {label: "Weight", name: "weight", widget: "number", default: 100}

